id: PFADDF0DE
initial_creation_type: input
source_metadata:
  Title: '-'
  Editor: '-'
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  svastyayanagāthā:
    Text Version: Romanized
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:11:25.714956'
last_modified_at: '2022-03-08T17:11:25.714964'
